$pdf_previewer = 'start evince';
push @generated_exts, 'pyg'; # Also clean up files generated by pygments
push @generated_exts, 'synctex.gz'; # Also clean up synctex files
push @generated_exts, 'run.xml'; # Also clean up logreq files
